# dev 开发环境
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brr-master?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource







